comptes/urls.py
from django.conf.urls import url, include

from django.contrib.auth.views import (
    login,
    logout,
    logout_then_login,
    password_change,
    password_change_done,

    password_reset,
    password_reset_done,
    password_reset_confirm,
    password_reset_complete,
)

from .views import connexion, dashboard, register, edit

urlpatterns = [
    #url(r'^connexion/$', connexion, name='connexion'),
    url(r'^dashboard/$', dashboard, name='dashboard'),
    url(r'^register/$', register, name='register'),
    url(r'^edit/$', edit, name='edit'),
    #Connexion et Deconnexion
    url(r'^login/$', login, name='login'),
    url(r'^logout/$', logout, name='logout'),
    url(r'^logout_then_login/$', logout_then_login, name='logout_then_login'),

    #Modifier Mot e Passe
    url(r'^password-change/$', password_change, name='password_change'),
    url(r'^password-change/done/$', password_change_done, name='password_change_done'),
    url(r'^password-reset/$', password_reset, name="password_reset"),
    url(r'^password-reset/done/$', password_reset_done, name="password_reset_done"),
    url(r'^password-reset/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', password_reset_confirm, name="password_reset_confirm"),
    url(r'^password-reset/complete/$',password_reset_complete, name="password_reset_complete"),
]

images/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from .views import images_create

urlpatterns = [
    url(r'^ajouter/', images_create, name='images_create'),
]

social_website/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

from .views import home

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url('', include('django.contrib.auth.urls')),
    url(r'^comptes/', include('comptes.urls', app_name="comptes", namespace="comptes")),
    url(r'^images/', include('images.urls', app_name="images", namespace="images")),
    #url('social-auth/', include('social.apps.django_app.urls', namespace="social")),
    url(r'social-auth/', include('social_django.urls', namespace='social')),
    url(r'', home, name='home'),
]

urlpatterns += [
    url(r'^captcha/', include('captcha.urls')),
]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load staticfiles %}

<!doctype html>
<html lang="fr">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% include 'css.html' %}
    {% block base_head %}{% endblock %}
    <title>{% block title %} Social Network{% endblock %}</title>
  </head>
  <body>
    {% include 'navbar.html' with brand_name="Bookmark" %}
     <div class="container">
        <div class="text-center">
            {% if messages %}
                <ul class="text-success">
                    {% for message in messages %}
                        <h3 class="{{ message.tags }}">
                            {{ message|safe }}
                        </h3>
                    {% endfor %}
                </ul>
            {% endif %}
        </div>

         {% block content %}
            {#le contenu de mon site#}
        {% endblock %}
     </div>

     {% include 'js.html' %}
  </body>
</html>

templates/base1.html
{% load staticfiles %}
<!doctype html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %} Social Network{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'js/jquery-ui.min.css' %}">

</head>
<body>

    <div id="header">
        <span class="logo">Bookmarks</span>
        {% if request.user.is_authenticated %}
            <ul class="menu">
                <li {% if section == "dashboard" %} class="selected" {% endif %}><a href="{% url 'comptes:dashboard' %}">Dashboard</a></li>
                <li {% if section == "images" %} class="selected" {% endif %}><a href="#"></a></li>
                <li {% if section == "people" %} class="selected" {% endif %}><a href="#"></a></li>
            </ul>
        {% endif %}

        <span class="user">
            {% if request.user.is_authenticated %}
                Bienvenus {{ request.user.username }}, <a href="{% url 'comptes:logout' %}">Deconnexion</a>
            {% else %}
                <a href="{% url 'comptes:login' %}">Connexion</a>
            {% endif %}
        </span>
    </div>

    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li class="{{ message.tags }}">
                    {{ message|safe }}
                </li>
            {% endfor %}
        </ul>
    {% endif %}

    <div id="container">
        {% block content %}
        {% endblock %}
    </div>

    <script src="{% static 'js/external/jquery/jquery.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/jquery-ui.min.css' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    <script>
      $('.datepicker').datepicker({
        format: 'dd/mm/yyyy',
        startDate: '-3d'
    });
    </script>
</body>
</html>

templates/css.html
{% load staticfiles %}
<!-- Bootstrap CSS -->
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'css/fa-svg-with-js.css' %}">
<link rel="stylesheet" href="{% static 'css/style.css' %}">

templates/index.html
{% extends 'base.html' %}
{% block title %}
    Accueil - {{ block.super }}
{% endblock %}
{% block content %}
    <div class="row">
    <div class="col-md-8">
        <h1>DJANGO SOCIAL NETWORK ?</h1>
        <p>
            DJANGO SOCIAL NETWORK est le Réseau Social des Développeurs <br />
            Et qui dit Développeurs, dit également partage de code Source ⌨ .<br />
            Gràce à cette plateforme, vous avez la possibilité de tisser des <br />
            liens d'amitiés avec d'autres dévéloppeurs, échanger du code sources ✍,<br />
            recevoir de l'aide en cas de problème sur l'un de vos projet et bien plus encores !<br />
            Alors n'hésiter surtout pas! <a href="{% url 'comptes:register' %}">à rejoindre la grande Communauté de Développeurs Django ✈</a>
        </p>
        <a class="btn btn-primary btn-lg" href="{% url 'comptes:login' %}">Connexion</a>
    </div>
    <div class="col-md-4">
        Social Connexion
        <ul>
            <a class="btn btn-social-icon btn-facebook" href="{% url "social:begin" "facebook" %}"><i class="fab fa-facebook-f"></i> Facebook</a><br/>
            <a class="btn btn-social-icon btn-twitter" href="{% url "social:begin" "twitter" %}"><i class="fab fa-twitter"></i> Twitter</a><br/>
            <a class="btn btn-social-icon btn-google-plus" href="{% url "social:begin" "google-oauth2" %}"><i class="fab fa-google"></i> Google</a><br/>
            <a class="btn btn-social-icon btn-github" href="{% url "social:begin" "github" %}"><i class="fab fa-github"></i> Github</a><br/>
            <a class="btn btn-social-icon btn-linkedin" href="{% url "social:begin" "linkedin" %}"><i class="fab fa-linkedin-in"></i> LinkedIn</a>
        </ul>
    </div>
    </div>
{% endblock %}

templates/js.html
{% load staticfiles %}
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'fontawesome/svg-with-js/js/fontawesome-all.min.js' %}"></script>

templates/navbar.html
{% url 'comptes:dashboard' as dashboard_url %}
{% url 'home' as home_url %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-3 custom-nav">
  <div class="container">
    <a href="{{ home_url }}" class="navbar-brand">Django Social NetWork</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
      aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item {% if request.path == dashboard_url %}active{% endif %}">
          <a class="nav-link" href="{{ dashboard_url }}">Bookmark
            <span class="sr-only">(current)</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Images</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">People</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle mr-auto" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true"
            aria-expanded="false">
            {% if user.is_authenticated %} {{ request.user.username }} {% else %} Compte {% endif %}
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            {% if request.user.is_authenticated %}
            <a class="dropdown-item" href="{% url 'comptes:edit' %}">Modifier Profile</a>
            <a class="dropdown-item" href="{% url 'comptes:password_change' %}">Modifier Password</a>
            <a class="dropdown-item" href="{% url 'comptes:logout' %}">Déconnexion</a>
            {% else %}
            <a class="dropdown-item" href="{% url 'comptes:login' %}">Connexion</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{% url 'comptes:register' %}">Inscription</a>
            {% endif %}
          </div>
        </li>
      </ul>
    </div>
  </div>
</nav>